[package]
name = "range-check"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-std = "0.5.0"
ark-ff = "0.5.0"
ark-ec = "0.5.0"
ark-relations = "0.5.1"
ark-groth16 = "0.5.0"
ark-bls12-381 = "0.5.0"
rand = "0.8"
rand_core="0.6"